---
- hosts: all

  gather_facts: no
  become: true

  roles:
    - apt
    - ntp
    - mariadb
    - php7
    - nginx
    - multi-wordpress
    - phpmyadmin

#  post_tasks:
#    - name: "Copiamos el archivo de inicio de LWP"

#  post_tasks:
#    - name: Eliminar webs
#      file:
#        path: /home/webs
#        state: absent
