---
## VARIABLES APT ##
aptget_update_cache_valid_time: 1800
aptget_distupgrade: true

aptget_install:
  - mc
  - nano
  - sysv-rc-conf
  - python-pip
  - python-dev
  - libmysqlclient-dev
  - python-jmespath
  - unzip
  - git
  - composer
#  - ngrok-client

## VARIABLES MARIADB ##
mariadb_root_password: lwp
mariadb_utiles_bd: true
mariadb_cron_backup: true
mariadb_cron_optimizacion: true

mariadb_databases:
  - wordpress_lwp
  - wordpress_stable
  - wordpress_nightly

mariadb_users:
  - name: "lwp"
    password: "lwp"
    priv: "*.*:ALL"


## VARIABLES PHP ##
php_max_input_vars: 1000
php_memory_limit: 512M
php_display_errors: Off
php_post_max_size: 48M
php_upload_max_filesize: 12M
php_max_file_uploads: 20
php_date_timezone: Europe/Madrid

## VARIABLES NGINX ##
nginx_vhosts_root: "/home/webs"

nginx_vhosts:
  - description: "Sitio Web Principal"
    default_server: true # Sólo debe existir uno como default server
    activado: true
    archivo_conf: "lwp.test.conf"
    dominio: "lwp.test"
    sin_www:  true
    ssl: false
    cache_nginx: false
    root: "{{ nginx_vhosts_root }}/lwp.test/public"
    logs: "{{ nginx_vhosts_root }}/lwp.test/logs"
    index: "index.html index.htm index.php"

  - description: "WordPress Rama Stable"
    activado: true
    archivo_conf: "stable.wordpress.test.conf"
    dominio: "stable.wordpress.test"
    sin_www:  true
    ssl: false
    cache_nginx: false
    root: "{{ nginx_vhosts_root }}/stable.wordpress.test/public"
    logs: "{{ nginx_vhosts_root }}/stable.wordpress.test/logs"
    index: "index.html index.htm index.php"

  - description: "WordPress Rama Nightly"
    activado: true
    archivo_conf: "nightly.wordpress.test.conf"
    dominio: "nightly.wordpress.test"
    sin_www:  true
    ssl: false
    cache_nginx: false
    root: "{{ nginx_vhosts_root }}/nightly.wordpress.test/public"
    logs: "{{ nginx_vhosts_root }}/nightly.wordpress.test/logs"
    index: "index.html index.htm index.php"

nginx_vhosts_activados:
  - lwp.test.conf
  - stable.wordpress.test.conf
  - nightly.wordpress.test.conf

## VARIABLES PHPMYADMIN ##
phpmyadmin_folder: "{{ nginx_vhosts_root }}/lwp.test/public/phpmyadmin"


## VARIABLES WORDPRESS ##
#wp_cli_webserver_user: www-data
#wp_cli_webserver_group: www-data

#wp_cli_packages: []

wp_cli_sites:
  - description: "Sitio Web de Admin General"
    locale: "es_ES"
    path: "{{ nginx_vhosts[0].root }}"
    version: "latest"

    db: "{{ mariadb_databases[0] }}"
    db_user: "{{ mariadb_users[0].name }}"
    db_pass: "{{ mariadb_users[0].password }}"
    db_host: "localhost"
    dp_prefix: "lwp_"

    url: "{{ nginx_vhosts[0].dominio }}"
    title: "LWP WordPress Control Panel Site"
    admin_user: "lwp"
    admin_password: "lwp"
    admin_email: "lwp@wordpress.test"

    plugins:
      - "MainWP Dashboard"
      - "BackUpWordPress"

  - description: "WordPress Stable"
    locale: "es_ES"
    path: "{{ nginx_vhosts[1].root }}"
    version: "latest"

    db: "{{ mariadb_databases[1] }}"
    db_user: "{{ mariadb_users[0].name }}"
    db_pass: "{{ mariadb_users[0].password }}"
    db_host: "localhost"
    dp_prefix: "lwp_"

    url: "{{ nginx_vhosts[1].dominio }}"
    title: "LWP WordPress Stable Site"
    admin_user: "lwp"
    admin_password: "lwp"
    admin_email: "lwp@wordpress.test"

    plugins: []

  - description: "WordPress Nightly"
    locale: "es_ES"
    path: "{{ nginx_vhosts[2].root }}"
    version: "latest"

    db: "{{ mariadb_databases[2] }}"
    db_user: "{{ mariadb_users[0].name }}"
    db_pass: "{{ mariadb_users[0].password }}"
    db_host: "localhost"
    dp_prefix: "lwp_"

    url: "{{ nginx_vhosts[2].dominio }}"
    title: "LWP WordPress Nightly Site"
    admin_user: "lwp"
    admin_password: "lwp"
    admin_email: "lwp@wordpress.test"

    plugins: []